### ISSUE TITLE
Unhelpful error when using a fully connected DAG.

### ISSUE THREAD

**Issue by RyutaroUchiyama** [Ax3man/phylopath#10]
Hello Wouter,

I have no problem running the example analysis that uses the 'rhino' data set and `rhino_tree`. But when I try to run the function `phylo_path()` using instead a tree downloaded from [10kTrees](http://10ktrees.nunn-lab.org/), I get errors such as:
```
Error in mutate_impl(.data, dots) : Evaluation error: comparison (6) is possible only for atomic and list types. 
```
and
```
Error in cor_fun(par, .x): object "phy" is not of class "phylo"
```
[10kTrees](http://10ktrees.nunn-lab.org/) is (as you might know) a resource used by many researchers, and the downloaded tree should be a properly formatted `phylo` object. Even when I use the `rhino` data set and the models as specified in your [tutorial](https://ax3man.github.io/phylopath/articles/intro_to_phylopath.html) but together with a 10kTrees primate tree (after replacing the `rhino` species names with a subset of the primate ones), I still get the former error listed above, so I assume the problem is the tree itself, although I'm not completely sure. I do have the most recent versions of the dependent packages.

I have no idea what I should be trying out, so any suggestions would be appreciated! If there is any other information or code that I could provide in order to clarify, please let me know.

Thanks,
Ryu

**Comment by Ax3man** [comment]
My best guess is that those tree files contain multiple trees, and you need to select one of them. For example, this works fine for me on the current CRAN release version:

```r
library(ape)

#Directly downloading and reading in the mentioned primate tree
oritatami_trees <- read.nexus("http://10ktrees.nunn-lab.org/Primates/downloads/version3/10kTrees_consensusTree_version3.nex")
oritatami_tree <- oritatami_trees[[1]]

fake_data <- data.frame(A = rnorm(301), B = rnorm(301), C = rnorm(301))
rownames(fake_data) <- oritatami_tree$tip.label

library(phylopath)
m <- list(DAG(A~B, B~C))
p <- phylo_path(m, fake_data, oritatami_tree)

```

If you continue to have a problem, please make sure to provide a reproducible example, perhaps similar to the one above, so I am able to reproduce your problem.

Thanks for the report!

**Comment by RyutaroUchiyama** [comment]
Thanks, your code works fine for me – it turns out that the problem was not with the tree, but rather with the model that I was using. When I use your code above but replace the line `m <- list(DAG(A~B, B~C))` with, for example `m <- list(DAG(A~B, B~C, A~C))`, I get an error when trying to run the `phylo_path()` function. But the latter DAG doesn't contain a directed cycle, and I can't figure out why having these three edges causes error. However, I'm new to graph theory, and it's possible that I'm missing something very basic. Do you know what the problem might be?

In any case, it turns out that I gave a misleading title to this report – apologies for that.

**Comment by Ax3man** [comment]
Ah ok, that clarifies things.

Basically, that model you are using is not testable. There are no variables that are predicted to be independent since all nodes are directly connected. Running `ggm::basiSet(DAG(A~B, B~C, A~C))` gives us `NULL `, i.e. no d-separation statements are found. This is a condition I should check for and give a more useful error message to.

**Comment by Ax3man** [comment]
A minimal reproducible example:

`phylo_path(list(DAG(BM~NL, NL~DD, BM~DD)), rhino, rhino_tree)`

**Comment by Ax3man** [comment]
Let me know if this doesn't solve your issue, and I can re-open this. Thanks for the report!
