### ISSUE TITLE
automating model generation

### ISSUE THREAD

**Issue by RyutaroUchiyama** [Ax3man/phylopath#11]
Hello again,

I've been trying to automate the model generation procedure so that all possible causal models, except for those that are either cyclic or fully connected, can be generated for some given number of variables without having to enter each model manually. Using the rhino data set to illustrate the point (and with three variables only), the main code looks like this:

```
library(phylopath)
library(gtools)

Nvar <- 3  #number of variables
#detach("package:ggm") # Disable ggm package because it masks DAG() function in 'phylopath::DAG'
dagobj <-  DAG(BM ~ LS, LS ~ DD) # generate a DAG with the three variables of interest
dagobj[1:Nvar,1:Nvar] <- matrix(0,Nvar,Nvar) # preset DAG matrix entries to 0

# --- Generate all possible binary strings, in order to allocate to DAG matrices
zerosones <- permutations(2,Nvar^2,v=c(0,1),repeats.allowed=TRUE)

# --- Remove models with reflexive edges (these are not DAGs)
cycles <- matrix(0,dim(zerosones)[1],1)
for (i in 1:Nvar){ cycles[which(zerosones[,Nvar*(i-1)+i] == 1)] <- 1 }
zerosones_2 <-  zerosones[-which(cycles==1),]

# --- Allocate binary strings to copies of the DAG object
models_1 <- rep(list(dagobj),dim(zerosones_2)[1])
for (i in 1:dim(zerosones_2)[1]){ models_1[[i]][,] <- zerosones_2[i,] }

# --- Further remove models, this time ones that have bidirectional edges
cycles_2 <- matrix(0,length(models_1),1)
for (k in 1:length(models_1)){ cycles_2[k] <- length(intersect( which(models_1[[k]] == t(models_1[[k]])), which(models_1[[k]]==1))) >0}   
models_2 <- models_1[which(cycles_2==0)]

# --- then do an additional check for cyclic models using ggm::isAcyclic()
#library(ggm)
cycles_3 <- matrix(0,length(models_2),1)
for (i in 1:length(models_2)){ cycles_3[i] <- ggm::isAcyclic(models_2[[i]])==0 }
models_3 <- models_2[which(cycles_3==0)]

# --- remove models for which d-separation cannot be evaluated due to full connectedness, using ggm::basiSet()
cycles_basisnull <- matrix(0,length(models_3),1)
for (i in 1:length(models_3)){ cycles_basisnull[i] <- is.null(ggm::basiSet(models_3[[i]])) } # ggm::basiSet
models_auto <- models_3[which(cycles_basisnull==0)] 

```
After running the above code, the list `models_auto` should contain 19 models. And it should be basically identical to the following manually constructed list: 

```
models_manual <- list(
  m1=DAG(BM~BM,LS~LS,DD~DD), m2=DAG(BM~LS,DD~DD), m3=DAG(BM~DD,LS~LS), m4=DAG(BM~DD,BM~LS), m5=DAG(LS~BM,DD~DD), m6=DAG(LS~BM,BM~DD), 
m7=DAG(LS~DD,BM~BM), m8=DAG(LS~DD,BM~LS),  m9=DAG(LS~DD,BM~DD), m10=DAG(LS~DD,LS~BM), m11=DAG(DD~BM,LS~LS), m12=DAG(DD~BM,BM~LS), 
m13=DAG(DD~BM,LS~BM), m14=DAG(DD~BM,LS~DD), m15=DAG(DD~LS,BM~BM), m16=DAG(DD~LS,BM~LS), m17=DAG(DD~LS,BM~DD), m18=DAG(DD~LS,LS~BM), m19=DAG(DD~LS,DD~BM)
) 
```
However, whereas `phylo_path()` works for `models_manual`, it doesn't work for `models_auto`. Specifically, `phylo_path(models_auto, rhino, rhino_tree)`
gives the following error: 
```
Error in mutate_impl(.data, dots) :  Evaluation error: comparison (6) is possible only for atomic and list types.
```

Do you have any idea why `phylo_path()` works for one but not the other? Is the apparent identity between `models_manual` and `models_auto` actually false? I need to automate model generation in this way because I'm going to scale up from 3 to 6 or 7 variables (an huge increase in the number of possible models), and also want to be able to approach the analysis in a theory-free manner. 

Any advice would be appreciated.

**Comment by Ax3man** [comment]
~~I have good and bad news; Your specific problem can be fixed relatively easily (at least in your example). What `phyolopath::DAG` is doing what you aren't, is to sort the variables each of the models by their hierarchy.~~

~~You can sort those models by simply running:~~

~~`models_auto_sorted <- lapply(models_auto, ggm::topSort)`~~

~~Now it will work fine.~~

~~The bad news is that the error you are seeing is actually indicative of a deeper problem that I need to solve, and you might run into the same error with a different set-up.~~

**Comment by Ax3man** [comment]
Alright, I have identified and fixed the underlying issue to this, making the above actually unnecessary.

Thanks for making a clear and reproducible error report!

You can check that all is working ok now by installing the github version of the package. Let me know if any issues remain. I hope you find the package useful.

(I'm not sure if it is a good idea to test all possible combinations models between seven variables.)

**Comment by RyutaroUchiyama** [comment]
It's working, thank you : )
