### ISSUE TITLE
Remove import of guide_train from ggraph

### ISSUE THREAD

**Issue by thomasp85** [Ax3man/phylopath#13]
This package imports and reexports `guide_train.edge_colourbar` from ggraph. As guide_train is now a proper exported S3 generic in ggplot2 the specific methods are no longer exported and can thus not be imported.

Can I get you to fix this and submit to CRAN?

https://github.com/Ax3man/phylopath/blob/b26003528531c601af7e1791ee38f9ccb081c1e9/R/internal.R#L265

**Comment by Ax3man** [comment]
Yes, absolutely. Does this mean I no longer have to the re-export, so can just remove this?

**Comment by thomasp85** [comment]
I would expect so yes. The S3 dispatching should take care of it

**Comment by Ax3man** [comment]
On it's way to CRAN.
