### ISSUE TITLE
Ensure compatibility with next ggraph version

### ISSUE THREAD

**Issue by thomasp85** [Ax3man/phylopath#14]
My reverse dependency check shows some problems between phylopath and the next ggraph version:

*   checking Rd cross-references ... WARNING
    ```
    Missing link or links in documentation object 'plot.DAG.Rd':
      ‘[ggraph:create_layout.igraph]{ggraph::create_layout.igraph()}’
    
    Missing link or links in documentation object 'plot.fitted_DAG.Rd':
      ‘[ggraph:create_layout.igraph]{ggraph::create_layout.igraph()}’
    
    See section 'Cross-references' in the 'Writing R Extensions' manual.
    ```

This is basically because the internal network representation has changed. I suggest you link directly to `create_layout` instead of to one of the methods. I plan on submitting ggraph to CRAN on September 1st and hope you'll be able to have a fix on CRAN by then.

best
Thomas

**Comment by Ax3man** [comment]
Thanks Thomas for the heads-up. Seems like an easy fix. I'm away for a conference this week, but I should be able to fix and submit to CRAN next week.

**Comment by Ax3man** [comment]
On CRAN now.
