### ISSUE TITLE
Altering values for the btol argument when using phylopath

### ISSUE THREAD

**Issue by LouisBell-Roberts** [Ax3man/phylopath#20]
Hi Wouter,

Thanks for making this very useful package!

Is there a way to alter the value for the 'btol' argument when using the phylo_path function? Normally, I am able to make this adjustment when using phyloglm but I can't seem to make this adjustment when using phylopath.

Do you have any suggestions?

Thanks,
Louis

**Comment by Ax3man** [comment]
Hi Louis,

Yes, arguments to `phylolm` or `phyloglm` can be passed through the `...` of various `phylopath` functions, including `phylo_path`. You should be able to just pass the `btol` parameter directly to `phylo_path`.

That said, there was bug in this previously that would make this not work, so make sure you are on version 1.1.3.

If it still does not work, and if you provide an example, I can probably help you get going.

**Comment by LouisBell-Roberts** [comment]
Thank you! I had previously been using an earlier version, but upon updating, this now works perfectly.

**Comment by Ax3man** [comment]
Ok, good to hear! Best of luck with your analysis.
