### ISSUE TITLE
Formal argument "boot" matched by multiple actual arguments

### ISSUE THREAD

**Issue by Joseph-Watts** [Ax3man/phylopath#21]
Hi there, 

great package, thanks for sharing and maintaining it! 

I was able to define boot values in an older version of phylo_path(). When I try and define boot values in the latest version (v.1.1.3 from CRAN) of phylopath I get the following error: "formal argument "boot" matched by multiple actual arguments." R and all my other packages are up to date.

Is there a change in how the boot argument is being passed on to phylolm in the updated version of phylopath? or am I just doing something silly here? The outcome variable is continuous if that helps and a sample of code is below. Happy to pass on any additional information if that would be useful.

Much appreciated,
Joseph

best_result <- phylo_path(best_models_DAG, 
                           data = data_use,
                           tree = pruned_tree, 
                           model = 'lambda',
                           method = "logistic_MPLE",
                           boot = 100)

Pruned tree to drop species not included in dat.
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Error: Fitting the following model:
    Unaffiliated ~ Education_Index + Life_expectancy_Index 
produced this error:
    formal argument "boot" matched by multiple actual arguments

**Comment by Ax3man** [comment]
Hi Joseph,

I think you would usually want to bootstrap to confidence intervals on the path coefficients of a given causal model. The `phylo_path` functions does model evaluation/comparison, but it doesn't actually fit the path coefficients. Usually, you run `best`, `choice` or `average` to get the coefficients afterwards, and you can get the confidence intervals there. Let me illustrate:

First, we do model comparison:

```r
library(phylopath)

candidates <- define_model_set(
  A = NL ~ BM,
  B = NL ~ LS,
  .common = c(LS ~ BM, DD ~ NL)
)
p <- phylo_path(candidates, rhino, rhino_tree)
summary(p)
```
Now, we can estimate the paths for e.g. the best model, using bootstrapping to get CIs:

```r
best_model <- best(p, boot = 10)
```

Or pick a particular model manually:

```r
model_B <- choice(p, 'B', boot = 10)
```

Or take the average of models (although these CIs are not based on bootstrapping but are approximate, coming from `MuMIn::par.avg`):

```r
avg_model <- average(p, cut_off = Inf, 'full')
```

Or finally, if you don't want to do this model selection, and just estimate a DAG directly, use `est_DAG` directly:

```r
my_model <- est_DAG(
  DAG = DAG(NL ~ BM, LS ~ BM, DD ~ NL),
  data = rhino, tree = rhino_tree, model = 'BM',
  boot = 10
)
```

Hope this makes sense. Let me know if you think it should work differently, or if I can make things more clear.

**Comment by Joseph-Watts** [comment]
Thanks very much for the detailed reply, very much appreciated. I have had success following your pointers but still cant get my earlier code working without changes. Great package, thanks once again!
