### ISSUE TITLE
Is it possible to obtain the baseline values from models?

### ISSUE THREAD

**Issue by Madeleinecg** [Ax3man/phylopath#23]
Hi Ax3man,

I would like to be able to convert the odds ratios obtained from phylopath models to probabilities to make results easier to interpret. For this I would need the baseline coefficients, which aren't provided. I presume it doesn't make sense to have a baseline coefficient when each phylopath model is comprised of many regression models, but thought I would ask just in case!

Many thanks

**Comment by Ax3man** [comment]
Hi Madeleine,

That's a good question. Odds ratios have always been quite intuitive to me, so I've just stuck to using that.

The multiple regression models are not necessarily a problem. For the estimation of a DAG, there is simply one separate model for each node that is a causal child (i.e. there is at least one causal path leading there). These models include intercepts (what you call baseline coefficients), but you are right that these are currently discarded.

You can easily fit the models yourself though, for a particular DAG. They are just calls to `phylolm::phyloglm`, in the case of binary outcomes. I can help if you have a reproducible example.

If you have a suggestion for how report the intercepts in a useful way to the user, let me know, and I can see whether it would be worth implementing in the package.

**Comment by Madeleinecg** [comment]
Thanks for your quick and helpful response.

I had thought all the coefficients were adjusted based on the results of the other models within the broader model. You can tell that my understanding is very shallow!

If my best model is [ X ~ Y + Z, A ~ X, Y ~ B ] and I want to get the baseline/intercept value for the binary variable Y (adjusted for Z), should I just run X ~ Y + Z? (I have tried this but the coefficients are not the same, so I guess not!)

**Comment by Ax3man** [comment]
I think that should be the right model, though keep in mind that phylopath standardizes all continuous variables.

**Comment by Madeleinecg** [comment]
I had forgotten! It's now matching and making a lot more sense. Thanks so much.
