### ISSUE TITLE
package `graph` dependency?

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [Ax3man/phylopath#24]
@Ax3man I need to update `phylosem` and `phylopath` is a dependency.  However, the code below fails with a warning about package `graph` not being available.  `graph` appears to be a dependency of `ggm`.  Any ideas on what's happening here?

```R
models_pp <- phylopath::define_model_set(
  one   = c(RS ~ DD),
  two   = c(DD ~ NL, RS ~ LS + DD),
  three = c(RS ~ NL),
  four  = c(RS ~ BM + NL),
  five  = c(RS ~ BM + NL + DD),
  six   = c(NL ~ RS, RS ~ BM),
  seven = c(NL ~ RS, RS ~ LS + BM),
  eight = c(NL ~ RS),
  nine  = c(NL ~ RS, RS ~ LS),
  .common = c(LS ~ BM, NL ~ BM, DD ~ NL)
)
```

**Comment by Ax3man** [comment]
Hey Jim, `graph` is a BioConductor package, and is not on CRAN.

https://bioconductor.org/packages/release/bioc/html/graph.html

**Comment by James-Thorson-NOAA** [comment]
Are you willing to change the phylopath DESCRIPTION to install graph upon `phylopath` installation?

**Comment by Ax3man** [comment]
Sure, do you have a reference on how to do that?

**Comment by James-Thorson-NOAA** [comment]
Hmm.  I know that it's possible using `Remotes:` but I don't know if doing so would pass CRAN checks.  

Is there any other way to modify `phylopath` to avoid `graph`?  I'm not sure how `ggm` stays on CRAN given that it Imports from a non-CRAN package :0

I guess my other option is to make the phylopath vignettes run conditional upon a local install of `graph`.  Would you prefer that I try that instead?

**Comment by Ax3man** [comment]
Ok, it seems it is possible but not/poorly documented:

https://bioinformatics.stackexchange.com/questions/3365/r-package-development-how-does-one-automatically-install-bioconductor-packages

https://github.com/r-lib/devtools/issues/700

I can add `graph` as an explicit dependency and add `biocViews:` to my description?

`ggm` provides core functionality to `phylopath` (it generates the d-sep statements) so it is not trivial to make that optional.

**Comment by James-Thorson-NOAA** [comment]
Yeah, I think my two preferred options are either:

1. Having you add graph to phylopath dependencies, so that all functions work for CRAN packages using phylopath as dependency; or
2. Me making those phylosem vignettes using phylopath conditional (in manner TBD)

I'd of course prefer option-1, but realize it's more work for you.  You wanna just try it out and get back to me, or other thoughts?

**Comment by Ax3man** [comment]
Ok, I have pushed a commit here that makes these changes. Testing quickly, it does appear to work when I uninstall `graph` and then run

     remotes::install_github("Ax3man/phylopath")
     
I *think* if I commit to CRAN it will solve the issue.. I can do that today if it looks good to you.

**Comment by Ax3man** [comment]
Or perhaps a superior solution is to submit a PR to [`ggm`](https://github.com/StaThin/ggm) to fix this upstream?

**Comment by James-Thorson-NOAA** [comment]
I can confirm that your modification to `phylopath` correctly installs `graph`.  My suggestion is to submit that version to CRAN, and also submit the issue to `ggm` to fix upstream.  For reasons I don't fully understand, TMB needs me to update `phylosem` (being a reverse-dependency), and I'd love to do the change sooner than `ggm` is likely to respond.

**Comment by James-Thorson-NOAA** [comment]
OK, another consideration ... I ran `phylosem` through `check_win_devel` and it passed all checks there using your github version locally.  So perhaps, given the way `phylosem` is set up, it doesn't really matter if the vignettes fail using the CRAN version of ggm and phylopath.  

Anyhoo, I'm gonna submit the updated version of `phylosem` to CRAN, and perhaps I don't have any pressing timeline after all.  But I do still think it's worth addressing the install issue in phylopath or ggm, so thanks for your help!

**Comment by Ax3man** [comment]
Ok great. I will reach out to `ggm` to see if it can be fixed there, since that's the nicer solution. I'll leave up the current working github version of `phylopath` until it is fixed.

Let me know if there are problems after all, and then I can push to CRAN.
