### ISSUE TITLE
Undeclared dependency on `graph`

### ISSUE THREAD

**Issue by mfansler** [Ax3man/phylopath#25]
The `graph` package is referenced but not declared in the DESCRIPTION as a dependency (Imports or Depends).

https://github.com/Ax3man/phylopath/blob/25e3f8de46df9168f941fa2e95d03de4ba1543bd/R/internal.R#L2

**Comment by mfansler** [comment]
Sorry, just noticed: https://github.com/Ax3man/phylopath/issues/24.

Is `graph` actually required by this package? If so, it should be in the DESCRIPTION (I believe CRAN is fine with declaring Bioconductor dependencies); if not, then it should not be referenced. If you only need `ggm` and they had broken builds prior to their properly declaring `graph`, then the minimum version of `ggm` should be raised.

**Comment by Ax3man** [comment]
Sorry, that was left over from me messing about trying to get `graph` to install automatically when using `install.packages()`. But no luck. There is no direct dependency on `graph` and `ggm` hasn't changed.
