### ISSUE TITLE
Error in number of dimensions with vignette example

### ISSUE THREAD

**Issue by ManuelaGonzalez** [Ax3man/phylopath#7]
Hi, I am running the example describe here https://cran.r-project.org/web/packages/phylopath/vignettes/intro_to_phylopath.html and when I run results <- phylo_path I get this error message
Error in s[nrow(s), ncol(s)] : incorrect number of dimensions

Any thoughts?
(I was trying first with my data and had the same problem so I decided to try the example). I restarted Rstudio and the problem persists)

**Comment by Ax3man** [comment]
Hi, the code in the vignette runs fine for me. Can you check what version you are running?

**Comment by ManuelaGonzalez** [comment]
Hi, I am using phylopath version 0.3.0 in RStudio 1.0.136 with R version 3.3.3 (2017-03-06)

**Comment by ManuelaGonzalez** [comment]
I updated both R to R version 3.4.1, and Rstudio to Version 1.0.153 and now I get a new error message

Error: Fitting the following model:
    DD ~ NL + BM 
produced this error:
    Error in recalc.corStruct(object[[i]], conLin): object 'corStruct_recalc' not found

**Comment by ManuelaGonzalez** [comment]
Forgot to mention I am working on a PC with Windows 7 Enterprsize Service Pack 1

**Comment by Ax3man** [comment]
I'm having a hard time even guessing what could be going on here. `recalc.corStruct` comes from `nlme`, so you might try reinstalling the `nlme` and `ape` packages.

And just to check, in a clean session these commands give the error?:

```
library(phylopath)

models <- list(
    one   = DAG(LS ~ BM, NL ~ BM, DD ~ NL, RS ~ DD),
    two   = DAG(LS ~ BM, NL ~ BM, DD ~ NL, RS ~ LS + DD)
)

result <- phylo_path(models, rhino, rhino_tree)
```

**Comment by ManuelaGonzalez** [comment]
Hi, looks like the problem was associated to older nlme and/or ape packages, I updated these and now both the example in the vignette and the simpler version you last suggested work. Thanks for your help! (Not sure if that is an option but it could be useful if when installing phylopath the most recent updates of ape and nlme were also installed).

**Comment by Ax3man** [comment]
Excellent, I'm happy this got sorted. Yes, I can add a minimum required version for those packages now that I know this can cause issues.

Thanks a lot for your bug report, and I hope the package will be useful for you.
