### ISSUE TITLE
phylo_path() produces error

### ISSUE THREAD

**Issue by hcliedtke** [Ax3man/phylopath#8]
Hi Wouter,

I am getting an error when running even the example of phylo_path()

code:

```
candidates <- list(A = DAG(LS ~ BM, NL ~ BM, DD ~ NL),
                   B = DAG(LS ~ BM, NL ~ LS, DD ~ NL))
p <- phylo_path(candidates, rhino, rhino_tree)

```
error: 

```
Error: Fitting the following model:
    DD ~ NL + BM 
produced this error:
    Error in nlme::gls(..., correlation = cor_fun(par, .x)): 
model must be a formula of the form "resp ~ pred"
```

I am running R 3.4, phylopath 0.3.0 and nlme 3.1-131 on  MAC OSX

Any ideas why that might be?

Thank you for your help and the great package!

Cheers,

Christoph

**Comment by Ax3man** [comment]
Hi Christoph,

That's unfortunate, the code runs fine for me. Can you try updating `ape`?

W.

**Comment by hcliedtke** [comment]
Hi wouter,

strange. ape (v4.1) and all other dependencies are up to date.

chris

**Comment by hcliedtke** [comment]
Hi wouter,

So if i roll back to phylopath 0.2.2 or earlier, I don't get this error. Not sure if that helps to diagnose the problem.

cheers,

chris

**Comment by Ax3man** [comment]
I will have a look at this soon, but am currently out without computer.

Yes, that might be useful information!

W.

----- Reply message -----

**Comment by Ax3man** [comment]
Ok, apparently an update in `purrr` breaks things but I haven't been notified. I can reproduce your error now and should be able to push a fix soon.

**Comment by Ax3man** [comment]
This should be fixed now, you can use `devtools::install_github("Ax3man/phylopath")` to install a working version.

Thanks for the report!

**Comment by hcliedtke** [comment]
thanks for the quick fix!

**Comment by Ax3man** [comment]
Ok, there's more `purrr` problems that need fixing, but I should get that all done today.

Edit: should all be good now, new version on CRAN.
